# Generated by Django 5.0.2 on 2024-02-28 16:48

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Categorie')),
                ('color', colorfield.fields.ColorField(default='#0D6EFD', image_field=None, max_length=25, samples=None, unique=True)),
            ],
        ),
    ]
