# Generated by Django 5.0.2 on 2024-02-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AddField(
            model_name='categorypost',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
