# Generated by Django 5.0.2 on 2024-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de lecture'),
        ),
    ]
