# Generated by Django 5.0.2 on 2024-03-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost'),
        ),
    ]
