# Generated by Django 5.0.2 on 2024-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_read_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Tag')),
                ('tag_slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='blog.tagpost'),
        ),
    ]
